use_frameworks!

platform :ios, '8.0'

target 'Tree_Example' do
  pod 'Tree', :path => '../'

  target 'Tree_Tests' do
    inherit! :search_paths

    
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "9.0"
#    end
#  end
#end
